from utilidades import clear_screen
from interfaz_usuario import mensaje, mensaje_2
from productos import calcular_cantidad_producto, agregar_item_movimiento_de_compra, eliminar_un_item_seleccionado_movimiento_de_compra, eliminar_varios_items_seleccionados_movimiento_de_compra, eliminar_todos_los_items_movimiento_de_compra, eliminar_item_movimiento_de_compra, editar_item_movimiento_de_compra, agregar_item_movimiento_de_venta, eliminar_un_item_seleccionado_movimiento_de_venta, eliminar_varios_items_seleccionados_movimiento_de_venta, eliminar_todos_los_items_movimiento_de_venta, eliminar_item_movimiento_de_venta, editar_item_movimiento_de_venta, agregar_item_movimiento_de_ajuste, eliminar_un_item_seleccionado_movimiento_de_ajuste, eliminar_varios_items_seleccionados_movimiento_de_ajuste, eliminar_todos_los_items_movimiento_de_ajuste, eliminar_item_movimiento_de_ajuste, editar_item_movimiento_de_ajuste, actualizar_movimientos_de_compra_de_productos, actualizar_movimientos_de_venta_de_productos, actualizar_movimientos_de_ajuste_de_productos, actualizar_atributos_producto_no_cantidad_no_precio, actualizar_precio_producto, actualizar_atributos_producto, actualizar_movimientos_producto, buscar_producto, buscar_producto_2, agregar_producto, buscar_codigo, encontrar_producto, encontrar_producto_por_descripcion, encontrar_producto_por_id



clear_screen()
mensaje_2('## Módulo PRODUCTOS')
print()
mensaje('# Función calcular_cantidad_producto')
help(calcular_cantidad_producto)
print()
mensaje('# Función agregar_item_movimiento_de_compra')
help(agregar_item_movimiento_de_compra)
print()
mensaje('# Función eliminar_un_item_seleccionado_movimiento_de_compra')
help(eliminar_un_item_seleccionado_movimiento_de_compra)
print()
mensaje('# Función eliminar_varios_items_seleccionados_movimiento_de_compra')
help(eliminar_varios_items_seleccionados_movimiento_de_compra)
print()
mensaje('# Función eliminar_todos_los_items_movimiento_de_compra')
help(eliminar_todos_los_items_movimiento_de_compra)
print()
mensaje('# Función eliminar_item_movimiento_de_compra')
help(eliminar_item_movimiento_de_compra)
print()
mensaje('# Función editar_item_movimiento_de_compra')
help(editar_item_movimiento_de_compra)
print()
mensaje('# Función agregar_item_movimiento_de_venta')
help(agregar_item_movimiento_de_venta)
print()
mensaje('# Función eliminar_un_item_seleccionado_movimiento_de_venta')
help(eliminar_un_item_seleccionado_movimiento_de_venta)
print()
mensaje('# Función eliminar_varios_items_seleccionados_movimiento_de_venta')
help(eliminar_varios_items_seleccionados_movimiento_de_venta)
print()
mensaje('# Función eliminar_todos_los_items_movimiento_de_venta')
help(eliminar_todos_los_items_movimiento_de_venta)
print()
mensaje('# Función eliminar_item_movimiento_de_venta')
help(eliminar_item_movimiento_de_venta)
print()
mensaje('# Función editar_item_movimiento_de_venta')
help(editar_item_movimiento_de_venta)
print()
mensaje('# Función agregar_item_movimiento_de_ajuste')
help(agregar_item_movimiento_de_ajuste)
print()
mensaje('# Función eliminar_un_item_seleccionado_movimiento_de_ajuste')
help(eliminar_un_item_seleccionado_movimiento_de_ajuste)
print()
mensaje('# Función eliminar_varios_items_seleccionados_movimiento_de_ajuste')
help(eliminar_varios_items_seleccionados_movimiento_de_ajuste)
print()
mensaje('# Función eliminar_todos_los_items_movimiento_de_ajuste')
help(eliminar_todos_los_items_movimiento_de_ajuste)
print()
mensaje('# Función eliminar_item_movimiento_de_ajuste')
help(eliminar_item_movimiento_de_ajuste)
print()
mensaje('# Función editar_item_movimiento_de_ajuste')
help(editar_item_movimiento_de_ajuste)
print()
mensaje('# Función actualizar_movimientos_de_compra_de_productos')
help(actualizar_movimientos_de_compra_de_productos)
print()
mensaje('# Función actualizar_movimientos_de_venta_de_productos')
help(actualizar_movimientos_de_venta_de_productos)
print()
mensaje('# Función actualizar_movimientos_de_ajuste_de_productos')
help(actualizar_movimientos_de_ajuste_de_productos)
print()
mensaje('# Función actualizar_atributos_producto_no_cantidad_no_precio')
help(actualizar_atributos_producto_no_cantidad_no_precio)
print()
mensaje('# Función actualizar_precio_producto')
help(actualizar_precio_producto)
print()
mensaje('# Función actualizar_atributos_producto')
help(actualizar_atributos_producto)
print()
mensaje('# Función actualizar_movimientos_producto')
help(actualizar_movimientos_producto)
print()
mensaje('# Función buscar_producto')
help(buscar_producto)
print()
mensaje('# Función buscar_producto_2')
help(buscar_producto_2)
print()
mensaje('# Función agregar_producto')
help(agregar_producto)
print()
mensaje('# Función buscar_codigo')
help(buscar_codigo)
print()
mensaje('# Función encontrar_producto')
help(encontrar_producto)
print()
mensaje('# Función encontrar_producto_por_descripcion')
help(encontrar_producto_por_descripcion)
print()
mensaje('# Función encontrar_producto_por_id')
help(encontrar_producto_por_id)