from utilidades import clear_screen
from interfaz_usuario import mensaje, mensaje_2
from database import traer_id_producto_desde_db, traer_id_producto_preex_desde_db, traer_id_mov_desde_db, cargar_lista_desde_db, cargar_lista_desde_db2, cargar_lista_con_id_desde_db, cargar_lista_con_id_desde_db_opcion, iniciar_carga_productos, iniciar_carga_productos_eliminados, recuperar_producto_eliminados_en_db, recuperar_movimientos_producto_en_db, eliminar_producto_en_db, eliminar_movimientos_producto_en_db, actualizar_item_movimiento_producto_en_db, agregar_producto_db, actualizar_item_producto_en_db, eliminar_item_producto_en_db, bloquear_usuario, agregar_ajuste_producto_db, agregar_ingreso_egreso_producto_db, agregar_usuario_en_db, recuperar_usuarios_eliminados_en_db, eliminar_usuario_en_db, actualizar_usuario_en_db, agregar_logs_usuario_en_db, generar_reportes_tiempo_usuario_en_db, generar_reportes_ventas_en_db, generar_reporte_de_bajo_stock, eliminar_logs_usuario_en_db


clear_screen()
mensaje_2('## Módulo DATABASE')
print()
mensaje('# Función traer_id_producto_desde_db')
print(traer_id_producto_desde_db.__doc__)
print()
mensaje('# Función traer_id_producto_preex_desde_db')
print(traer_id_producto_preex_desde_db.__doc__)
print()
mensaje('# Función traer_id_mov_desde_db')
print(traer_id_mov_desde_db.__doc__)
print()
mensaje('# Función cargar_lista_desde_db')
print(cargar_lista_desde_db.__doc__)
print()
mensaje('# Función cargar_lista_desde_db2')
print(cargar_lista_desde_db2.__doc__)
print()
mensaje('# Función cargar_lista_con_id_desde_db')
print(cargar_lista_con_id_desde_db.__doc__)
print()
mensaje('# Función cargar_lista_con_id_desde_db_opcion')
print(cargar_lista_con_id_desde_db_opcion.__doc__)
print()
mensaje('# Función iniciar_carga_productos')
print(iniciar_carga_productos.__doc__)
print()
mensaje('# Función iniciar_carga_productos_eliminados')
print(iniciar_carga_productos_eliminados.__doc__)
print()
mensaje('# Función recuperar_producto_eliminados_en_db')
print(recuperar_producto_eliminados_en_db.__doc__)
print()
mensaje('# Función recuperar_movimientos_producto_en_db')
print(recuperar_movimientos_producto_en_db.__doc__)
print()
mensaje('# Función eliminar_producto_en_db')
print(eliminar_producto_en_db.__doc__)
print()
mensaje('# Función eliminar_movimientos_producto_en_db')
print(eliminar_movimientos_producto_en_db.__doc__)
print()
mensaje('# Función actualizar_item_movimiento_producto_en_db')
print(actualizar_item_movimiento_producto_en_db.__doc__)
print()
mensaje('# Función agregar_producto_db')
print(agregar_producto_db.__doc__)
print()
mensaje('# Función actualizar_item_producto_en_db')
print(actualizar_item_producto_en_db.__doc__)
print()
mensaje('# Función eliminar_item_producto_en_db')
print(eliminar_item_producto_en_db.__doc__)
print()
mensaje('# Función bloquear_usuario')
print(bloquear_usuario.__doc__)
print()
mensaje('# Función agregar_ajuste_producto_db')
print(agregar_ajuste_producto_db.__doc__)
print()
mensaje('# Función agregar_ingreso_egreso_producto_db')
print(agregar_ingreso_egreso_producto_db.__doc__)
print()
mensaje('# Función agregar_usuario_en_db')
print(agregar_usuario_en_db.__doc__)
print()
mensaje('# Función recuperar_usuarios_eliminados_en_db')
print(recuperar_usuarios_eliminados_en_db.__doc__)
print()
mensaje('# Función eliminar_usuario_en_db')
print(eliminar_usuario_en_db.__doc__)
print()
mensaje('# Función actualizar_usuario_en_db')
print(actualizar_usuario_en_db.__doc__)
print()
mensaje('# Función agregar_logs_usuario_en_db')
print(agregar_logs_usuario_en_db.__doc__)
print()
mensaje('# Función generar_reportes_tiempo_usuario_en_db')
print(generar_reportes_tiempo_usuario_en_db.__doc__)
print()
mensaje('# Función generar_reportes_ventas_en_db')
print(generar_reportes_ventas_en_db.__doc__)
print()
mensaje('# Función generar_reporte_de_bajo_stock')
print(generar_reporte_de_bajo_stock.__doc__)
print()
mensaje('# Función eliminar_logs_usuario_en_db')
print(eliminar_logs_usuario_en_db.__doc__)



