from utilidades import clear_screen
from interfaz_usuario import mensaje_2, mensaje, imprimir_lista, imprimir_lista_dos_valores, mostrar_menu, mostrar_lista_eliminados, mostrar_productos_entre_cantidades_stock, mostrar_lista, mostrar_lista_usuarios, mostrar_lista_usuarios_eliminados, mostrar_lista_usuarios_seleccion, mostrar_detalle_cambio_stock, mostrar_detalle_cambio_stock_seleccion, reportar_tiempo_usuarios_por_dia_entrefechas, reportar_tiempo_por_usuario_total_entrefechas, reportar_ventas_por_usuario_por_dia_entrefechas, reportar_ventas_por_usuario_total_entrefechas, opcion_menu, opcion_menu_con_0, opcion_menu_2, opcion_menu_2_con_0



clear_screen()
mensaje_2('## Módulo INTERFAZ USUARIO')
print()
mensaje('# Función imprimir_lista')
help(imprimir_lista)
print()
mensaje('# Función imprimir_lista_dos_valores')
help(imprimir_lista_dos_valores)
print()
mensaje('# Función mensaje')
help(mensaje)
print()
mensaje('# Función mensaje_2')
help(mensaje_2)
print()
mensaje('# Función mostrar_menu')
help(mostrar_menu)
print()
mensaje('# Función mostrar_lista_eliminados')
help(mostrar_lista_eliminados)
print()
mensaje('# Función mostrar_productos_entre_cantidades_stock')
help(mostrar_productos_entre_cantidades_stock)
print()
mensaje('# Función mostrar_lista')
help(mostrar_lista)
print()
mensaje('# Función mostrar_lista_usuarios')
help(mostrar_lista_usuarios)
print()
mensaje('# Función mostrar_lista_usuarios_eliminados')
help(mostrar_lista_usuarios_eliminados)
print()
mensaje('# Función mostrar_lista_usuarios_seleccion')
help(mostrar_lista_usuarios_seleccion)
print()
mensaje('# Función mostrar_detalle_cambio_stock')
help(mostrar_detalle_cambio_stock)
print()
mensaje('# Función mostrar_detalle_cambio_stock_seleccion')
help(mostrar_detalle_cambio_stock_seleccion)
print()
mensaje('# Función reportar_tiempo_usuarios_por_dia_entrefechas')
help(reportar_tiempo_usuarios_por_dia_entrefechas)
print()
mensaje('# Función reportar_tiempo_por_usuario_total_entrefechas')
help(reportar_tiempo_por_usuario_total_entrefechas)
print()
mensaje('# Función reportar_ventas_por_usuario_por_dia_entrefechas')
help(reportar_ventas_por_usuario_por_dia_entrefechas)
print()
mensaje('# Función reportar_ventas_por_usuario_total_entrefechas')
help(reportar_ventas_por_usuario_total_entrefechas)
print()
mensaje('# Función opcion_menu')
help(opcion_menu)
print()
mensaje('# Función opcion_menu_con_0')
help(opcion_menu_con_0)
print()
mensaje('# Función opcion_menu_2')
help(opcion_menu_2)
print()
mensaje('# Función opcion_menu_2_con_0')
help(opcion_menu_2_con_0)


