from utilidades import clear_screen
from interfaz_usuario import mensaje, mensaje_2
from menu import menu_restriccion_de_acceso, menu_agregar_producto, submenu_mostrar_productos, menu_ver_productos, submenu_buscar_producto_por_id, submenu_buscar_producto_por_descripcion, submenu_buscar_producto_por_codigo_marca, submenu_buscar_producto_por_modelo_marca, submenu_buscar_producto_por_marca, submenu_buscar_producto_por_categoria, menu_buscar_producto, submenu_actualizar_producto_por_id, submenu_actualizar_producto_por_descripcion, submenu_actualizar_producto_por_codigo, submenu_actualizar_producto_por_marca, submenu_actualizar_producto_por_modelo, submenu_actualizar_producto_por_categoria, menu_actualizar_producto, menu_actualizar_movimientos_producto, submenu_actualizar_movimientos_producto, submenu_eliminar_producto_por_id, submenu_eliminar_producto_por_descripcion, submenu_eliminar_producto_por_codigo, submenu_eliminar_productos_de_una_marca, submenu_eliminar_productos_de_un_modelo_marca, menu_eliminar_producto, submenu_gestionar_productos_eliminados, submenu_crear_un_backup, submenu_volver_desde_backup, menu_mantenimiento, submenu_ver_usuarios_del_sistema, submenu_agregar_usuario_al_sistema, submenu_editar_datos_de_usuario_del_sistema, submenu_eliminar_usuario_del_sistema, submenu_gestionar_usuarios_eliminados, submenu_generar_reporte_de_tiempo_de_uso, submenu_generar_reporte_de_ventas, menu_gestionar_usuarios, submenu_eliminar_logs_usuarios


clear_screen()
mensaje_2('## Módulo MENU')
print()
mensaje('# Función menu_restriccion_de_acceso')
print(menu_restriccion_de_acceso.__doc__)
print()
mensaje('# Función menu_agregar_producto')
print(menu_agregar_producto.__doc__)
print()
mensaje('# Función submenu_mostrar_productos')
print(submenu_mostrar_productos.__doc__)
print()
mensaje('# Función menu_ver_productos')
print(menu_ver_productos.__doc__)
print()
mensaje('# Función submenu_buscar_producto_por_id')
print(submenu_buscar_producto_por_id.__doc__)
print()
mensaje('# Función submenu_buscar_producto_por_descripcion')
print(submenu_buscar_producto_por_descripcion.__doc__)
print()
mensaje('# submenu_buscar_producto_por_codigo_marca')
print(submenu_buscar_producto_por_codigo_marca.__doc__)
print()
mensaje('# Función submenu_buscar_producto_por_modelo_marca')
print(submenu_buscar_producto_por_modelo_marca.__doc__)
print()
mensaje('# Función submenu_buscar_producto_por_marca')
print(submenu_buscar_producto_por_marca.__doc__)
print()
mensaje('# Función submenu_buscar_producto_por_categoria')
print(submenu_buscar_producto_por_categoria.__doc__)
print()
mensaje('# Función menu_buscar_producto')
print(menu_buscar_producto.__doc__)
print()
mensaje('# Función submenu_actualizar_producto_por_id')
print(submenu_actualizar_producto_por_id.__doc__)
print()
mensaje('# Función submenu_actualizar_producto_por_descripcion')
print(submenu_actualizar_producto_por_descripcion.__doc__)
print()
mensaje('# Función submenu_actualizar_producto_por_codigo')
print(submenu_actualizar_producto_por_codigo.__doc__)
print()
mensaje('# Función submenu_actualizar_producto_por_marca')
print(submenu_actualizar_producto_por_marca.__doc__)
print()
mensaje('# Función submenu_actualizar_producto_por_modelo')
print(submenu_actualizar_producto_por_modelo.__doc__)
print()
mensaje('# Función submenu_actualizar_producto_por_categoria')
print(submenu_actualizar_producto_por_categoria.__doc__)
print()
mensaje('# Función menu_actualizar_producto')
print(menu_actualizar_producto.__doc__)
print()
mensaje('# Función submenu_actualizar_movimientos_producto')
print(submenu_actualizar_movimientos_producto.__doc__)
print()
mensaje('# Función menu_actualizar_movimientos_producto')
print(menu_actualizar_movimientos_producto.__doc__)
print()
mensaje('# Función submenu_eliminar_producto_por_id')
print(submenu_eliminar_producto_por_id.__doc__)
print()
mensaje('# Función submenu_eliminar_producto_por_descripcion')
print(submenu_eliminar_producto_por_descripcion.__doc__)
print()
mensaje('# Función submenu_eliminar_producto_por_codigo')
print(submenu_eliminar_producto_por_codigo.__doc__)
print()
mensaje('# Función submenu_eliminar_productos_de_una_marca')
print(submenu_eliminar_productos_de_una_marca.__doc__)
print()
mensaje('# Función submenu_eliminar_productos_de_un_modelo_marca')
print(submenu_eliminar_productos_de_un_modelo_marca.__doc__)
print()
mensaje('# Función menu_eliminar_producto')
print(menu_eliminar_producto.__doc__)
print()
mensaje('# Función submenu_gestionar_productos_eliminados')
print(submenu_gestionar_productos_eliminados.__doc__)
print()
mensaje('# Función submenu_crear_un_backup')
print(submenu_crear_un_backup.__doc__)
print()
mensaje('# Función submenu_volver_desde_backup')
print(submenu_volver_desde_backup.__doc__)
print()
mensaje('# Función menu_mantenimiento')
print(menu_mantenimiento.__doc__)
print()
mensaje('# Función  submenu_ver_usuarios_del_sistema')
print( submenu_ver_usuarios_del_sistema.__doc__)
print()
mensaje('# Función submenu_agregar_usuario_al_sistema')
print(submenu_agregar_usuario_al_sistema.__doc__)
print()
mensaje('# Función submenu_editar_datos_de_usuario_del_sistema')
print(submenu_editar_datos_de_usuario_del_sistema.__doc__)
print()
mensaje('# Función submenu_eliminar_usuario_del_sistema')
print(submenu_eliminar_usuario_del_sistema.__doc__)
print()
mensaje('# Función submenu_gestionar_usuarios_eliminados')
print(submenu_gestionar_usuarios_eliminados.__doc__)
print()
mensaje('# Función submenu_generar_reporte_de_tiempo_de_uso')
print(submenu_generar_reporte_de_tiempo_de_uso.__doc__)
print()
mensaje('# Función submenu_generar_reporte_de_ventas')
print(submenu_generar_reporte_de_ventas.__doc__)
print()
mensaje('# Función menu_gestionar_usuarios')
print(menu_gestionar_usuarios.__doc__)
print()
mensaje('# Función submenu_eliminar_logs_usuarios')
print(submenu_eliminar_logs_usuarios.__doc__)

