from utilidades import clear_screen
from interfaz_usuario import mensaje, mensaje_2
from productos import calcular_cantidad_producto, agregar_item_movimiento_de_compra, eliminar_un_item_seleccionado_movimiento_de_compra, eliminar_varios_items_seleccionados_movimiento_de_compra, eliminar_todos_los_items_movimiento_de_compra, eliminar_item_movimiento_de_compra, editar_item_movimiento_de_compra, agregar_item_movimiento_de_venta, eliminar_un_item_seleccionado_movimiento_de_venta, eliminar_varios_items_seleccionados_movimiento_de_venta, eliminar_todos_los_items_movimiento_de_venta, eliminar_item_movimiento_de_venta, editar_item_movimiento_de_venta, agregar_item_movimiento_de_ajuste, eliminar_un_item_seleccionado_movimiento_de_ajuste, eliminar_varios_items_seleccionados_movimiento_de_ajuste, eliminar_todos_los_items_movimiento_de_ajuste, eliminar_item_movimiento_de_ajuste, editar_item_movimiento_de_ajuste, actualizar_movimientos_de_compra_de_productos, actualizar_movimientos_de_venta_de_productos, actualizar_movimientos_de_ajuste_de_productos, actualizar_atributos_producto_no_cantidad_no_precio, actualizar_precio_producto, actualizar_atributos_producto, actualizar_movimientos_producto, buscar_producto, buscar_producto_2, agregar_producto, buscar_codigo, encontrar_producto, encontrar_producto_por_descripcion, encontrar_producto_por_id



clear_screen()
mensaje_2('## Módulo PRODUCTOS')
print()
mensaje('# Función calcular_cantidad_producto')
print(calcular_cantidad_producto.__doc__)
print()
mensaje('# Función agregar_item_movimiento_de_compra')
print(agregar_item_movimiento_de_compra.__doc__)
print()
mensaje('# Función eliminar_un_item_seleccionado_movimiento_de_compra')
print(eliminar_un_item_seleccionado_movimiento_de_compra.__doc__)
print()
mensaje('# Función eliminar_varios_items_seleccionados_movimiento_de_compra')
print(eliminar_varios_items_seleccionados_movimiento_de_compra.__doc__)
print()
mensaje('# Función eliminar_todos_los_items_movimiento_de_compra')
print(eliminar_todos_los_items_movimiento_de_compra.__doc__)
print()
mensaje('# Función eliminar_item_movimiento_de_compra')
print(eliminar_item_movimiento_de_compra.__doc__)
print()
mensaje('# Función editar_item_movimiento_de_compra')
print(editar_item_movimiento_de_compra.__doc__)
print()
mensaje('# Función agregar_item_movimiento_de_venta')
print(agregar_item_movimiento_de_venta.__doc__)
print()
mensaje('# Función eliminar_un_item_seleccionado_movimiento_de_venta')
print(eliminar_un_item_seleccionado_movimiento_de_venta.__doc__)
print()
mensaje('# Función eliminar_varios_items_seleccionados_movimiento_de_venta')
print(eliminar_varios_items_seleccionados_movimiento_de_venta.__doc__)
print()
mensaje('# Función eliminar_todos_los_items_movimiento_de_venta')
print(eliminar_todos_los_items_movimiento_de_venta.__doc__)
print()
mensaje('# Función eliminar_item_movimiento_de_venta')
print(eliminar_item_movimiento_de_venta.__doc__)
print()
mensaje('# Función editar_item_movimiento_de_venta')
print(editar_item_movimiento_de_venta.__doc__)
print()
mensaje('# Función agregar_item_movimiento_de_ajuste')
print(agregar_item_movimiento_de_ajuste.__doc__)
print()
mensaje('# Función eliminar_un_item_seleccionado_movimiento_de_ajuste')
print(eliminar_un_item_seleccionado_movimiento_de_ajuste.__doc__)
print()
mensaje('# Función eliminar_varios_items_seleccionados_movimiento_de_ajuste')
print(eliminar_varios_items_seleccionados_movimiento_de_ajuste.__doc__)
print()
mensaje('# Función eliminar_todos_los_items_movimiento_de_ajuste')
print(eliminar_todos_los_items_movimiento_de_ajuste.__doc__)
print()
mensaje('# Función eliminar_item_movimiento_de_ajuste')
print(eliminar_item_movimiento_de_ajuste.__doc__)
print()
mensaje('# Función editar_item_movimiento_de_ajuste')
print(editar_item_movimiento_de_ajuste.__doc__)
print()
mensaje('# Función actualizar_movimientos_de_compra_de_productos')
print(actualizar_movimientos_de_compra_de_productos.__doc__)
print()
mensaje('# Función actualizar_movimientos_de_venta_de_productos')
print(actualizar_movimientos_de_venta_de_productos.__doc__)
print()
mensaje('# Función actualizar_movimientos_de_ajuste_de_productos')
print(actualizar_movimientos_de_ajuste_de_productos.__doc__)
print()
mensaje('# Función actualizar_atributos_producto_no_cantidad_no_precio')
print(actualizar_atributos_producto_no_cantidad_no_precio.__doc__)
print()
mensaje('# Función actualizar_precio_producto')
print(actualizar_precio_producto.__doc__)
print()
mensaje('# Función actualizar_atributos_producto')
print(actualizar_atributos_producto.__doc__)
print()
mensaje('# Función actualizar_movimientos_producto')
print(actualizar_movimientos_producto.__doc__)
print()
mensaje('# Función buscar_producto')
print(buscar_producto.__doc__)
print()
mensaje('# Función buscar_producto_2')
print(buscar_producto_2.__doc__)
print()
mensaje('# Función agregar_producto')
print(agregar_producto.__doc__)
print()
mensaje('# Función buscar_codigo')
print(buscar_codigo.__doc__)
print()
mensaje('# Función encontrar_producto')
print(encontrar_producto.__doc__)
print()
mensaje('# Función encontrar_producto_por_descripcion')
print(encontrar_producto_por_descripcion.__doc__)
print()
mensaje('# Función encontrar_producto_por_id')
print(encontrar_producto_por_id.__doc__)