from utilidades import clear_screen
from interfaz_usuario import mensaje_2, mensaje, imprimir_lista, imprimir_lista_dos_valores, mostrar_menu, mostrar_lista_eliminados, mostrar_productos_entre_cantidades_stock, mostrar_lista, mostrar_lista_usuarios, mostrar_lista_usuarios_eliminados, mostrar_lista_usuarios_seleccion, mostrar_detalle_cambio_stock, mostrar_detalle_cambio_stock_seleccion, reportar_tiempo_usuarios_por_dia_entrefechas, reportar_tiempo_por_usuario_total_entrefechas, reportar_ventas_por_usuario_por_dia_entrefechas, reportar_ventas_por_usuario_total_entrefechas, opcion_menu, opcion_menu_con_0, opcion_menu_2, opcion_menu_2_con_0



clear_screen()
mensaje_2('## Módulo INTERFAZ USUARIO')
print()
mensaje('# Función imprimir_lista')
print(imprimir_lista.__doc__)
print()
mensaje('# Función imprimir_lista_dos_valores')
print(imprimir_lista_dos_valores.__doc__)
print()
mensaje('# Función mensaje')
print(mensaje.__doc__)
print()
mensaje('# Función mensaje_2')
print(mensaje_2.__doc__)
print()
mensaje('# Función mostrar_menu')
print(mostrar_menu.__doc__)
print()
mensaje('# Función mostrar_lista_eliminados')
print(mostrar_lista_eliminados.__doc__)
print()
mensaje('# Función mostrar_productos_entre_cantidades_stock')
print(mostrar_productos_entre_cantidades_stock.__doc__)
print()
mensaje('# Función mostrar_lista')
print(mostrar_lista.__doc__)
print()
mensaje('# Función mostrar_lista_usuarios')
print(mostrar_lista_usuarios.__doc__)
print()
mensaje('# Función mostrar_lista_usuarios_eliminados')
print(mostrar_lista_usuarios_eliminados.__doc__)
print()
mensaje('# Función mostrar_lista_usuarios_seleccion')
print(mostrar_lista_usuarios_seleccion.__doc__)
print()
mensaje('# Función mostrar_detalle_cambio_stock')
print(mostrar_detalle_cambio_stock.__doc__)
print()
mensaje('# Función mostrar_detalle_cambio_stock_seleccion')
print(mostrar_detalle_cambio_stock_seleccion.__doc__)
print()
mensaje('# Función reportar_tiempo_usuarios_por_dia_entrefechas')
print(reportar_tiempo_usuarios_por_dia_entrefechas.__doc__)
print()
mensaje('# Función reportar_tiempo_por_usuario_total_entrefechas')
print(reportar_tiempo_por_usuario_total_entrefechas.__doc__)
print()
mensaje('# Función reportar_ventas_por_usuario_por_dia_entrefechas')
print(reportar_ventas_por_usuario_por_dia_entrefechas.__doc__)
print()
mensaje('# Función reportar_ventas_por_usuario_total_entrefechas')
print(reportar_ventas_por_usuario_total_entrefechas.__doc__)
print()
mensaje('# Función opcion_menu')
print(opcion_menu.__doc__)
print()
mensaje('# Función opcion_menu_con_0')
print(opcion_menu_con_0.__doc__)
print()
mensaje('# Función opcion_menu_2')
print(opcion_menu_2.__doc__)
print()
mensaje('# Función opcion_menu_2_con_0')
print(opcion_menu_2_con_0.__doc__)


