from utilidades import clear_screen
from interfaz_usuario import mensaje, mensaje_2
from menu import menu_restriccion_de_acceso, menu_agregar_producto, submenu_mostrar_productos, menu_ver_productos, submenu_buscar_producto_por_id, submenu_buscar_producto_por_descripcion, submenu_buscar_producto_por_codigo_marca, submenu_buscar_producto_por_modelo_marca, submenu_buscar_producto_por_marca, submenu_buscar_producto_por_categoria, menu_buscar_producto, submenu_actualizar_producto_por_id, submenu_actualizar_producto_por_descripcion, submenu_actualizar_producto_por_codigo, submenu_actualizar_producto_por_marca, submenu_actualizar_producto_por_modelo, submenu_actualizar_producto_por_categoria, menu_actualizar_producto, menu_actualizar_movimientos_producto, submenu_actualizar_movimientos_producto, submenu_eliminar_producto_por_id, submenu_eliminar_producto_por_descripcion, submenu_eliminar_producto_por_codigo, submenu_eliminar_productos_de_una_marca, submenu_eliminar_productos_de_un_modelo_marca, menu_eliminar_producto, submenu_gestionar_productos_eliminados, submenu_crear_un_backup, submenu_volver_desde_backup, menu_mantenimiento, submenu_ver_usuarios_del_sistema, submenu_agregar_usuario_al_sistema, submenu_editar_datos_de_usuario_del_sistema, submenu_eliminar_usuario_del_sistema, submenu_gestionar_usuarios_eliminados, submenu_generar_reporte_de_tiempo_de_uso, submenu_generar_reporte_de_ventas, menu_gestionar_usuarios, submenu_eliminar_logs_usuarios


clear_screen()
mensaje_2('## Módulo MENU')
print()
mensaje('# Función menu_restriccion_de_acceso')
help(menu_restriccion_de_acceso)
print()
mensaje('# Función menu_agregar_producto')
help(menu_agregar_producto)
print()
mensaje('# Función submenu_mostrar_productos')
help(submenu_mostrar_productos)
print()
mensaje('# Función menu_ver_productos')
help(menu_ver_productos)
print()
mensaje('# Función submenu_buscar_producto_por_id')
help(submenu_buscar_producto_por_id)
print()
mensaje('# Función submenu_buscar_producto_por_descripcion')
help(submenu_buscar_producto_por_descripcion)
print()
mensaje('# submenu_buscar_producto_por_codigo_marca')
help(submenu_buscar_producto_por_codigo_marca)
print()
mensaje('# Función submenu_buscar_producto_por_modelo_marca')
help(submenu_buscar_producto_por_modelo_marca)
print()
mensaje('# Función submenu_buscar_producto_por_marca')
help(submenu_buscar_producto_por_marca)
print()
mensaje('# Función submenu_buscar_producto_por_categoria')
help(submenu_buscar_producto_por_categoria)
print()
mensaje('# Función menu_buscar_producto')
help(menu_buscar_producto)
print()
mensaje('# Función submenu_actualizar_producto_por_id')
help(submenu_actualizar_producto_por_id)
print()
mensaje('# Función submenu_actualizar_producto_por_descripcion')
help(submenu_actualizar_producto_por_descripcion)
print()
mensaje('# Función submenu_actualizar_producto_por_codigo')
help(submenu_actualizar_producto_por_codigo)
print()
mensaje('# Función submenu_actualizar_producto_por_marca')
help(submenu_actualizar_producto_por_marca)
print()
mensaje('# Función submenu_actualizar_producto_por_modelo')
help(submenu_actualizar_producto_por_modelo)
print()
mensaje('# Función submenu_actualizar_producto_por_categoria')
help(submenu_actualizar_producto_por_categoria)
print()
mensaje('# Función menu_actualizar_producto')
help(menu_actualizar_producto)
print()
mensaje('# Función submenu_actualizar_movimientos_producto')
help(submenu_actualizar_movimientos_producto)
print()
mensaje('# Función menu_actualizar_movimientos_producto')
help(menu_actualizar_movimientos_producto)
print()
mensaje('# Función submenu_eliminar_producto_por_id')
help(submenu_eliminar_producto_por_id)
print()
mensaje('# Función submenu_eliminar_producto_por_descripcion')
help(submenu_eliminar_producto_por_descripcion)
print()
mensaje('# Función submenu_eliminar_producto_por_codigo')
help(submenu_eliminar_producto_por_codigo)
print()
mensaje('# Función submenu_eliminar_productos_de_una_marca')
help(submenu_eliminar_productos_de_una_marca)
print()
mensaje('# Función submenu_eliminar_productos_de_un_modelo_marca')
help(submenu_eliminar_productos_de_un_modelo_marca)
print()
mensaje('# Función menu_eliminar_producto')
help(menu_eliminar_producto)
print()
mensaje('# Función submenu_gestionar_productos_eliminados')
help(submenu_gestionar_productos_eliminados)
print()
mensaje('# Función submenu_crear_un_backup')
help(submenu_crear_un_backup)
print()
mensaje('# Función submenu_volver_desde_backup')
help(submenu_volver_desde_backup)
print()
mensaje('# Función menu_mantenimiento')
help(menu_mantenimiento)
print()
mensaje('# Función  submenu_ver_usuarios_del_sistema')
help( submenu_ver_usuarios_del_sistema)
print()
mensaje('# Función submenu_agregar_usuario_al_sistema')
help(submenu_agregar_usuario_al_sistema)
print()
mensaje('# Función submenu_editar_datos_de_usuario_del_sistema')
help(submenu_editar_datos_de_usuario_del_sistema)
print()
mensaje('# Función submenu_eliminar_usuario_del_sistema')
help(submenu_eliminar_usuario_del_sistema)
print()
mensaje('# Función submenu_gestionar_usuarios_eliminados')
help(submenu_gestionar_usuarios_eliminados)
print()
mensaje('# Función submenu_generar_reporte_de_tiempo_de_uso')
help(submenu_generar_reporte_de_tiempo_de_uso)
print()
mensaje('# Función submenu_generar_reporte_de_ventas')
help(submenu_generar_reporte_de_ventas)
print()
mensaje('# Función menu_gestionar_usuarios')
help(menu_gestionar_usuarios)
print()
mensaje('# Función submenu_eliminar_logs_usuarios')
help(submenu_eliminar_logs_usuarios)

